import { writable, derived } from 'svelte/store';

const STORAGE_KEY = 'rest2mcp_lang';

function getInitialLang() {
  try {
    return localStorage.getItem(STORAGE_KEY) || 'pt';
  } catch {
    return 'pt';
  }
}

export const lang = writable(getInitialLang());

export const toggleLang = () => {
  lang.update(v => {
    const next = v === 'pt' ? 'en' : 'pt';
    try { localStorage.setItem(STORAGE_KEY, next); } catch { }
    return next;
  });
};

const dict = {
  pt: {
    'nav.about': 'Sobre',
    'nav.features': 'Recursos',
    'nav.pricing': 'Preços',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacto',
    'nav.login': 'Entrar',
    'nav.enter': 'Entrar',
    'nav.go_to_dashboard': 'Ir para Dashboard',
    'hero.tag': 'v1.0.0',
    'hero.title': 'Converte qualquer API REST em MCP',
    'hero.sub': 'Conecte as suas APIs REST ao Claude, GPT ou qualquer cliente MCP em segundos. 100% na nuvem, sem servidor local.',
    'hero.cta': 'Criar Servidor Grátis',
    'hero.badge.seconds': 'Segundos de configuração',
    'hero.badge.zero': 'Zero código necessário',
    'hero.badge.openapi': 'Suporta OpenAPI 3.0 + Swagger 2.0',
    'hero.badge.auth': 'Auth segura via Web',
    'hero.cli.label': 'CLI oficial',
    'hero.cli.desc': 'Gere os seus servidores MCP direto do terminal: crie, ligue ao seu editor (VS Code, Claude, Cursor, OpenCode...) e consulte logs sem sair da linha de comandos.',
    'hero.cli.copy': 'Copiar',
    'hero.cli.copied': 'Copiado!',
    'about.label': '// 01 — Sobre o projeto',
    'about.title': 'Por que este projeto existe?',
    'about.p1': 'LLMs modernos como Claude e GPT têm capacidades incríveis, mas não conseguem interagir diretamente com APIs REST. O Protocolo MCP (Model Context Protocol) resolve isso, mas exige que cada API tenha um servidor MCP dedicado.',
    'about.p2': 'O rest2mcp elimina essa barreira: fornece a URL da spec OpenAPI/Swagger, e o servidor gera automaticamente as ferramentas MCP — sem escrever uma única linha de código.',
    'about.problem': 'Cada API REST precisa de um servidor MCP dedicado. Criar um à mão para cada endpoint é inviável.',
    'about.solution': 'Conversão automática de specs OpenAPI/Swagger para ferramentas MCP — 100% na nuvem, sem instalação local.',
    'about.how': 'Como funciona?',
    'about.how_desc': 'O rest2mcp corre na nossa infraestrutura na nuvem. Fornece a URL da spec OpenAPI/Swagger e o servidor gera automaticamente as ferramentas MCP correspondentes — sem instalar nada localmente. O LLM pode chamar endpoints, fazer login, e interagir com a API como se fosse uma extensão nativa.',
    'security.label': '// Segurança',
    'security.title': 'Sua privacidade é nossa prioridade.',
    'security.badge': 'Arquitetura Zero-Knowledge',
    'security.stateless': 'Stateless',
    'security.stateless_desc': 'Não possuímos banco de dados de credenciais. Os tokens vivem apenas na memória efémera durante a sessão.',
    'security.e2e': 'End-to-End',
    'security.e2e_desc': 'A conexão é feita diretamente entre o LLM e a sua infraestrutura através da nossa ponte.',
    'security.audit': 'Auditável',
    'security.audit_desc': 'Logs transparentes para você monitorar exatamente o que a IA está acessando.',
    'features.label': '// 03 — Recursos',
    'features.title': 'Tudo o que precisas, pronto a usar.',
    'features.desc': 'Oito recursos que tornam o rest2mcp a escolha mais rápida para conectar LLMs às tuas APIs.',
    'feat.anyapi': 'Qualquer API, Zero Código',
    'feat.anyapi_desc': 'Apenas configura a URL da spec OpenAPI. O servidor gera automaticamente todas as ferramentas MCP — sem desenvolver nada.',
    'feat.auth': 'Auth Segura via Web',
    'feat.auth_desc': 'O login é feito diretamente no nosso portal — as suas credenciais nunca passam pelo contexto da IA. O token é injetado automaticamente nas chamadas seguintes.',
    'feat.merge': 'Múltiplas APIs + Merge',
    'feat.merge_desc': 'Combina várias APIs num único servidor MCP com namespaces. Suporta merge de servidores locais e remotos.',
    'feat.compat': 'Compatibilidade Total',
    'feat.compat_desc': 'Totalmente compatível com especificações OpenAPI 3.0 e 3.1, bem como com o formato clássico Swagger 2.0.',
    'feat.logs': 'Logs em Tempo Real',
    'feat.logs_desc': 'Monitoriza todas as chamadas das IAs às tuas ferramentas: método, status, duração, request e response completos.',
    'feat.proxy': 'Proxy SSE + HTTP',
    'feat.proxy_desc': 'Suporta Server-Sent Events (SSE) e Streamable HTTP. Ligações persistentes e contínuas com a tua API.',
    'feat.secure': 'Autenticação Segura',
    'feat.secure_desc': 'Login seguro com Google, GitHub ou e-mail/senha. Gestão de sessão, recuperação de senha e perfis de utilizador protegidos.',
    'feat.stripe': 'Pagamentos Stripe',
    'feat.stripe_desc': 'Plano Pro com pagamentos seguros via Stripe. Checkout integrado, gestão automática de subscrições e notificações webhook.',
    'pricing.label': '// Planos',
    'pricing.title': 'Escolha o melhor plano.',
    'pricing.desc': 'Do hobby ao enterprise — o rest2mcp adapta-se às suas necessidades.',
    'pricing.hobby': 'Hobby',
    'pricing.hobby_price': 'R$ 0',
    'pricing.hobby_desc': 'Para testes e experimentação',
    'pricing.hobby.feat1': '1 Servidor Ativo',
    'pricing.hobby.feat2': '1 Servidor Merge',
    'pricing.hobby.feat3': 'Logs das últimas 24h',
    'pricing.hobby.feat4': '10 requisições/minuto',
    'pricing.hobby.feat5': 'Transporte SSE + HTTP',
    'pricing.hobby.cta': 'Começar Grátis',
    'pricing.pro': 'Pro',
    'pricing.pro_price': '$9.90',
    'pricing.pro_month': '/mês',
    'pricing.pro_desc': 'Para uso profissional',
    'pricing.pro.feat1': '10 Servidores Ativos',
    'pricing.pro.feat2': '10 Servidores Merge',
    'pricing.pro.feat3': 'Logs completos (sem expiração)',
    'pricing.pro.feat4': '100 requisições/minuto',
    'pricing.pro.feat5': 'Prioridade alta (sem cold-start)',
    'pricing.pro.feat6': 'Suporte a APIs privadas via Tunnel',
    'pricing.pro.cta': 'Assinar Pro',
    'pricing.enterprise': 'Enterprise',
    'pricing.enterprise_price': 'Sob Consulta',
    'pricing.enterprise_desc': 'Para organizações',
    'pricing.enterprise.feat1': 'Servidores Ilimitados',
    'pricing.enterprise.feat2': 'Merge Ilimitado',
    'pricing.enterprise.feat3': 'Logs completos + exportação',
    'pricing.enterprise.feat4': 'Rate limits personalizados',
    'pricing.enterprise.feat5': 'Suporte dedicado + SLA',
    'pricing.enterprise.cta': 'Consultar Vendas',
    'pricing.popular': 'POPULAR',
    'dashboard.label': '// Dashboard',
    'dashboard.title': 'Gerencie seus servidores em tempo real.',
    'dashboard.desc': 'Interface simples e direta para criar, monitorar e gerenciar as suas pontes MCP.',
    'dashboard.my_servers': 'Meus Servidores',
    'faq.label': '// FAQ',
    'faq.title': 'Perguntas frequentes.',
    'faq.desc': 'Dúvidas comuns de desenvolvedores sobre o rest2mcp.',
    'faq.q1': 'Quais especificações são aceitas?',
    'faq.a1': 'Aceitamos especificações OpenAPI 3.0 e 3.1 nativamente, e também oferecemos total compatibilidade com Swagger 2.0.',
    'faq.q2': 'Preciso instalar alguma coisa?',
    'faq.a2': 'Não. O rest2mcp corre 100% na nuvem. Apenas precisa de um cliente MCP (VS Code, Claude Desktop, Cursor, etc.).',
    'faq.q3': 'Como funciona a autenticação?',
    'faq.a3': 'O servidor deteta automaticamente endpoints de login na spec. O LLM pode fazer login via ferramenta MCP e o token é gerido automaticamente. Também suportamos OAuth (Google, GitHub).',
    'faq.q4': 'Posso combinar várias APIs?',
    'faq.a4': 'Sim. Pode combinar várias APIs num único servidor MCP. Cada API mantém o seu contexto separado.',
    'faq.q5': 'O que é o recurso de Merge Server?',
    'faq.a5': 'O Merge Server permite unificar múltiplos servidores MCP (sejam locais ou remotos na nuvem) sob um único ponto de acesso. A IA interage com todas as ferramentas de forma integrada.',
    'faq.q6': 'O que são logs em tempo real?',
    'faq.a6': 'Cada chamada das IAs às ferramentas é registada: método, status, duração, request e response. Pode filtrar, exportar (JSON/CSV) e inspecionar detalhes.',
    'faq.q7': 'Como funciona o plano Pro?',
    'faq.a7': 'O plano Pro custa $9.90/mês e dá acesso a 10 servidores, logs completos, 100 req/min, prioridade alta e suporte a APIs privadas via tunnel. Pagamento via PayPal com subscrição mensal.',
    'contact.label': '// 04 — Contacto e Suporte',
    'contact.title': 'Entre em contacto connosco.',
    'contact.desc': 'Tem alguma dúvida, feedback ou precisa de suporte personalizado? Envie-nos uma mensagem diretamente.',
    'contact.name': 'O seu nome',
    'contact.email': 'O seu e-mail',
    'contact.subject': 'Assunto da mensagem',
    'contact.message': 'Escreva a sua mensagem aqui...',
    'contact.send': 'Enviar Mensagem',
    'contact.or': 'Se preferir, pode enviar um e-mail diretamente para:',
    'config.label': '// 07 — Configuração',
    'config.title': 'Clientes MCP suportados.',
    'config.desc': 'O rest2mcp funciona com qualquer cliente MCP. Basta apontar para a nossa ponte na nuvem.',
    'config.more': 'E mais...',
    'footer.desc': 'Versão 1.0.0 · Autor: Matias Fernando',
    'footer.about': 'Sobre o Projeto',
    'footer.support': 'Suporte',
    'footer.rights': '© 2026 rest2mcp. Todos os direitos reservados. Nenhum dado é retido nos nossos servidores.',
    'login.title': 'Entrar na sua Conta',
    'login.sub': 'Selecione o seu provedor favorito para continuar',
    'login.google': 'Entrar com o Google',
    'login.github': 'Entrar com o GitHub',
    'login.email_divider': 'ou use o seu email',
    'login.email_placeholder': 'O seu email',
    'login.password_placeholder': 'Palavra-passe',
    'login.confirm_placeholder': 'Confirmar palavra-passe',
    'login.forgot': 'Esqueci a minha palavra-passe',
    'login.submit': 'Entrar',
    'login.cancel': 'Cancelar',
    'login.register_title': 'Criar Conta',
    'login.register_sub': 'Registe-se para começar a usar',
    'login.register_btn': 'Registar',
    'login.toggle_register': 'Não tem conta? Registar-se',
    'login.toggle_login': 'Já tem conta? Entrar',
    'login.registered': 'Registo efetuado com sucesso!',
    'login.check_email': 'Confirme o seu email. Verifique a caixa de entrada (e spam).',
    'forgot.title': 'Redefinir Palavra-passe',
    'forgot.sub': 'Receberá um email com instruções para redefinir a sua palavra-passe',
    'forgot.email_placeholder': 'O seu email',
    'forgot.send': 'Enviar Email',
    'forgot.cancel': 'Cancelar',
    'forgot.sending': 'A enviar...',
    'forgot.sent': 'Email enviado! Verifique a sua caixa de entrada (e spam).',
    'paypal.title': 'Assinar Pro',
    'paypal.sub': 'Finalize a sua subscrição mensal',
    'paypal.cancel': 'Cancelar',
    'paypal.activated': 'Subscrição ativada!',
    'dashboard.nav.title': 'Meus Servidores',
    'dashboard.online': 'online',
    'dashboard.offline': 'offline',
    'dashboard.copy_url': 'Copy Connection URL',
    'dashboard.live_logs': 'Live Logs',
    'common.loading': 'A carregar...',
    'common.error': 'Erro',
    'common.save': 'Salvar',
    'common.confirm': 'Confirmar',
    'common.cancel': 'Cancelar',
    'common.create': 'Criar',
    'common.edit': 'Editar',
    'common.delete': 'Remover',
    'common.close': 'Fechar',
    'tool.params': 'Parâmetros:',
    'tool.none': 'nenhum',
    'tool.no_args': 'Esta tool não requer argumentos.',
    'tool.run': 'Executar',
    'tool.running': 'A executar...',
    'tool.result': 'Resultado',
    'tool.raw': 'Raw JSON',
    'tool.formatted': 'Formatado',
    'tool.error': 'Tool retornou erro',
    'tool.run_error': 'Erro ao executar tool',
    'tool.array_hint': 'JSON array ou separado por vírgulas',
    'store.loading': 'A carregar loja...',
    'store.error': 'Erro ao carregar servidores. Tente novamente.',
    'store.empty': 'Nenhum servidor encontrado.',
    'store.load_more': 'Carregar mais servidores',
    'pagination.prev': 'Anterior',
    'pagination.next': 'Seguinte',
    'store.remote': 'Remoto',
    'store.hybrid': 'Híbrido',
    'store.local': 'Local',
    'store.tools': 'tools',
    'store.modal.title': 'MCP Store',
    'server.edit': 'Editar',
    'server.inspect': 'Inspecionar',
    'server.tools': 'Ver Tools',
    'server.merge': 'Merge',
    'server.deactivate': 'Desativar',
    'server.activate': 'Ativar',
    'server.delete': 'Remover',
    'server.unmerge': 'Desfazer Merge',
    'server.created': 'Servidor criado com sucesso.',
    'server.deleted': 'Servidor removido com sucesso.',
    'server.activated': 'Servidor ativado com sucesso.',
    'server.deactivated': 'Servidor desativado com sucesso.',
    'server.merged': 'Servidor merged criado com sucesso.',
    'server.unmerged': 'Merge desfeito com sucesso.',
    'modal.create.title': 'Criar Servidor',
    'modal.create.name': 'Nome do Servidor',
    'modal.create.spec_url': 'URL do OpenAPI Spec',
    'modal.create.transport': 'Transporte',
    'modal.create.btn': 'Criar Servidor',
    'modal.create.creating': 'Criando...',
    'modal.edit.title': 'Editar Servidor',
    'modal.merge.title': 'Merge de Servidores',
    'modal.merge.target': 'Selecione um servidor...',
    'modal.merge.btn': 'Criar Servidor Merged',
    'modal.merge.creating': 'A criar...',
    'modal.merge.local': 'Fusão de servidores no rest2mcp com namespace automático',
    'modal.merge.sandbox': 'Instalação temporária de um servidor MCP via npx, pipx ou uv (ou JSON personalizado)',
    'menu.inspect': 'Inspecionar',
    'menu.edit': 'Editar',
    'menu.tools': 'Ver Tools',
    'menu.merge': 'Merge',
    'menu.deactivate': 'Desativar',
    'menu.activate': 'Ativar',
    'menu.delete': 'Remover',
    'menu.unmerge': 'Desfazer Merge',
    'confirm.delete': 'Remover este servidor permanentemente?',
    'confirm.unmerge': 'Desfazer merge deste servidor?',
    'tools.modal.title': 'Tools:',
    'tools.modal.loading': 'A carregar tools...',
    'tools.modal.empty': 'Nenhuma tool disponível.',
    'tools.modal.close': 'Fechar',
    'auth.login_error': 'Token inválido ou expirado',
    'auth.session_ended': 'Sessão terminada.',
    'auth.login_redirect': 'Redirecionando para',
    'env.title': 'Variáveis de Ambiente / Headers',
    'env.auth_placeholder': 'Bearer seu-token-aqui',
    'env.auth_desc': 'Token de autenticação para servidores remotos',
    'merge.local_tab': 'Local',
    'merge.sandbox_tab': 'Sandbox',
    'merge.name_placeholder': 'Ex: Minha API (Merged)',
    'merge.error_required': 'Informe o nome do servidor merged.',
    'merge.error_json': 'JSON inválido. Verifique a sintaxe.',
    'merge.error_target': 'Selecione um servidor alvo.',
    'merge.error_env': 'Preencha todos os campos obrigatórios de ambiente.',
    'merge.search_label': 'Pesquisar servidores...',
    'merge.sort_label': 'Ordenar',
    'not_found': 'Servidor não encontrado',
    'server.not_found': 'ID do servidor não disponível',
    'profile.plan': 'plano',
    'profile.servers': 'servidores',
    'profile.token_hint': 'Use este token no cabeçalho Authorization: Bearer <token> para autenticar pedidos à API.',
    'login.error': 'Falha ao carregar servidores da loja',
    'toolcall.error': 'Erro ao listar tools',
    'dashboard.new_server': 'Novo Servidor',
    'dashboard.loading_servers': 'Carregando servidores',
    'dashboard.load_error': 'Erro ao carregar servidores:',
    'dashboard.retry': 'Tentar novamente',
    'dashboard.empty': 'Nenhum servidor ainda.',
    'dashboard.empty_hint': 'Clique em + Novo Servidor para começar.',
    'dashboard.page_sub': 'Gerencie suas pontes MCP na nuvem',
    'dashboard.current_plan': 'Plano Atual',
    'dashboard.hobby_badge': '✦ Hobby',
    'dashboard.active_servers': 'Servidores ativos',
    'dashboard.log_retention': 'Retenção de logs',
    'dashboard.gateway': 'Gateway',
    'dashboard.servers_label': 'Servidores',
    'dashboard.plan_label': 'Plano',
    'dashboard.subscription': 'Subscrição',
    'dashboard.subscribe': 'Assinar Pro — $9.90/mês',
    'dashboard.logs_title': 'Logs',
    'dashboard.filter_tool': 'Filtrar tool...',
    'dashboard.all': 'Todos',
    'dashboard.success_2xx': '2xx Sucesso',
    'dashboard.error_4xx': '4xx Erro',
    'dashboard.error_5xx': '5xx Erro',
    'dashboard.waiting_logs': 'Aguardando atividade...',
    'dashboard.no_calls': 'Nenhuma chamada ainda...',
    'dashboard.clear_logs_confirm': 'Limpar todos os logs deste servidor?',
    'dashboard.logs_cleared': 'Logs limpos com sucesso.',
    'dashboard.clear_logs_error': 'Erro ao limpar logs:',
    'dashboard.gateway_ok': 'ok · {count} ativos',
    'dashboard.gateway_offline': 'offline',
    'dashboard.api_unavailable': 'API indisponível',
    'dashboard.merged_badge': 'Merged',
    'dashboard.log_detail_title': 'Detalhe do Log',
    'dashboard.log_detail_sub': 'Requisição e resposta completas',
    'dashboard.request_body_label': 'Request Body',
    'dashboard.response_body_label': 'Response Body',
    'dashboard.empty_body': '(vazio)',
    'dashboard.export_json': 'Exportar JSON',
    'dashboard.export_csv': 'Exportar CSV',
    'dashboard.clear_logs_btn': 'Limpar logs',
    'dashboard.refresh': 'Atualizar',
    'dashboard.log_server_placeholder': 'Servidor...',
    'dashboard.now': 'agora',
    'dashboard.options': 'Mais opções',
    'profile.token': 'Token de Acesso (Bearer)',
    'profile.copy': 'Copiar',
    'profile.copied': 'Copiado ✓',
    'profile.account_details': 'Detalhes da Conta',
    'profile.user_id': 'User ID',
    'profile.email': 'Email',
    'profile.provider': 'Fornecedor',
    'profile.password': 'Palavra-passe',
    'profile.change_password': 'Alterar Palavra-passe',
    'profile.new_password': 'Nova palavra-passe (mín. 6 caracteres)',
    'profile.password_min': 'A nova palavra-passe deve ter pelo menos 6 caracteres.',
    'profile.password_min_reset': 'A palavra-passe deve ter pelo menos 6 caracteres.',
    'profile.service_unavailable': 'Serviço indisponível de momento. Tente recarregar a página.',
    'profile.saving': 'A guardar...',
    'profile.password_changed': 'Palavra-passe alterada com sucesso!',
    'profile.resetting': 'A redefinir...',
    'profile.password_reset_success': 'Palavra-passe redefinida com sucesso!',
    'profile.logout': 'Terminar Sessão',
    'profile.servers_label': 'Servidores',
    'profile.rpm_label': 'RPM',
    'profile.member_since': 'Membro desde',
    'profile.not_authenticated': '(não autenticado)',
    'profile.user_default': 'Utilizador',
    'profile.close_btn': 'Fechar',
    'profile.view_profile': 'Ver perfil',
    'profile.sign_out_title': 'Sair da conta',
    'profile.reset_password_title': 'Redefinir Palavra-passe',
    'profile.reset_password_sub': 'Escolha uma nova palavra-passe para a sua conta',
    'profile.new_password_field': 'Nova Palavra-passe',
    'profile.password_min_chars': 'Mínimo 6 caracteres',
    'profile.reset_password_btn': 'Redefinir Palavra-passe',
    'auth.redirecting': 'Redirecionando para',
    'auth.ending_session': 'Terminando sessão...',
    'auth.popup_blocked': 'O popup blocker impediu a abertura do MCP Inspector.\nAbra manualmente:',
    'server.toggle_on': 'ativado',
    'server.toggle_off': 'desativado',
    'server.toggle_error': 'Erro ao alterar status:',
    'server.delete_error': 'Erro ao remover:',
    'server.unmerge_error': 'Erro ao desfazer merge:',
    'server.name_required': 'Informe o nome do servidor.',
    'server.spec_required': 'Informe a URL do OpenAPI Spec.',
    'server.edit_name_required': 'Nome não pode ficar vazio.',
    'server.edit_spec_url_required': 'Informe a URL do OpenAPI Spec.',
    'server.create_error': 'Erro ao criar servidor:',
    'server.update_ok': 'Servidor atualizado com sucesso.',
    'server.update_error': 'Erro ao atualizar servidor:',
    'server.merge_name_required': 'Informe o nome do servidor merged.',
    'server.merge_config_required': 'Informe a configuração JSON do servidor.',
    'server.merge_error_json': 'JSON inválido. Verifique a sintaxe.',
    'server.merge_error_env': 'Preencha todos os campos obrigatórios de ambiente.',
    'server.merge_command_required': 'JSON precisa do campo command ou mcpServers.',
    'server.merge_target_required': 'Selecione um servidor alvo.',
    'server.merge_error_local': 'Erro no merge local:',
    'server.merge_error_remote': 'Erro no merge remoto:',
    'server.merge_error_sandbox': 'Erro no merge sandbox:',
    'server.inspector_starting': 'A iniciar MCP Inspector...',
    'server.inspector_no_url': 'O backend não retornou um URL de inspector.',
    'server.inspector_error': 'Erro ao iniciar inspector:',
    'store.hosting': 'Hosting',
    'store.categories': 'Categorias',
    'store.search_placeholder': 'Buscar servidores MCP...',
    'store.sort_relevance': 'Relevância',
    'store.sort_stars': '★ Estrelas GitHub',
    'store.sort_tools': '🛠 Mais ferramentas',
    'store.sort_name_asc': 'Nome A-Z',
    'store.sort_name_desc': 'Nome Z-A',
    'store.modal_sub': 'Encontre e instale servidores MCP públicos',
    'store.package_not_found': "Pacote '{pkg}' não encontrado no npm. Fallback ativado.",
    'store.fallback_activated': 'Fallback ativado.',
    'store.using_alternative': 'A usar:',
    'store.install_btn': 'Instalar a partir da loja',
    'merge.local_title': 'Servidores no rest2mcp',
    'merge.local_desc': 'Fusão de servidores no rest2mcp com namespace automático',
    'merge.sandbox_desc': 'Instalação temporária de um servidor MCP via npx, pipx ou uv (ou JSON personalizado)',
    'merge.sandbox_title': 'Sandbox / JSON',
    'merge.merge_label': 'Nome do Servidor Merged',
    'merge.merge_placeholder': 'Ex: API Unificada',
    'merge.target_label': 'Servidor alvo',
    'merge.target_hint': 'Servidor rest2mcp que será fundido com o servidor fonte',
    'merge.config_label': 'Config JSON',
    'merge.config_hint': 'Comando/args do servidor MCP. Suporta mcpServers, url (remoto), command (stdio), tools (transformações) e env.',
    'modal.create.sub': 'Registre uma nova API para ser convertida em MCP',
    'modal.create.name_placeholder': 'Ex: Minha API Principal',
    'modal.create.url_placeholder': 'https://api.exemplo.com/openapi.json',
    'modal.create.transport_http': 'Streamable HTTP (recomendado)',
    'modal.create.transport_sse': 'SSE (legado)',
    'modal.edit.sub': 'Altere as configurações do servidor MCP',
    'modal.edit.name_label': 'Nome do Servidor',
    'modal.edit.name_placeholder': 'Ex: Minha API',
    'modal.edit.transport_label': 'Transporte',
    'modal.edit.status_label': 'Status',
    'modal.edit.status_online': 'Online',
    'modal.edit.status_offline': 'Offline',
    'modal.edit.saving': 'Salvando...',
    'notifications.supabase_error': 'Falha ao inicializar Supabase:',
    'notifications.supabase_not_configured': 'Supabase não configurado.',
    'notifications.paypal_error': 'Erro ao processar pagamento.',
    'notifications.paypal_activated': 'Subscrição ativada!',
    'notifications.log_detail_error': 'Erro ao carregar detalhe do log:',
    'dashboard.log_meta_tool': 'Tool',
    'dashboard.log_meta_method': 'Method',
    'dashboard.log_meta_status': 'Status',
    'dashboard.log_meta_duration': 'Duração',
    'dashboard.log_meta_date': 'Data',
    'auth.login_title': 'Login na API',
    'auth.needs_login': 'Precisa de Login',
    'auth.authenticating': 'A autenticar…',
    'auth.authenticate': 'Autenticar',
    'auth.login_desc': 'O login é feito diretamente no seu navegador — as suas credenciais nunca passam pelo contexto da IA.',
    'auth.why_title': 'Por que preferimos a autenticação Web em vez do LLM?',
    'auth.why_desc': 'Na arquitetura moderna de integração de IA, a segurança dos seus dados é a prioridade máxima. Permitir que um Large Language Model (LLM) manipule senhas ou faça login em seu nome introduz riscos desnecessários.',
    'auth.step1_title': '1. Login Direto (Human-in-the-loop)',
    'auth.step1_desc': 'Quando insere as suas credenciais aqui no portal, elas viajam diretamente do seu navegador para a API de destino. O agente de IA está "cego" a esta transação.',
    'auth.step2_title': '2. Gestão de Sessão Efêmera',
    'auth.step2_desc': 'Recebemos o Token (JWT ou similar) de volta da API e o guardamos de forma segura na sessão ativa do seu servidor MCP.',
    'auth.step3_title': '3. Injeção Transparente',
    'auth.step3_desc': 'Sempre que a IA precisa usar uma ferramenta que exige permissão (como "criar tarefa" ou "ver perfil"), o nosso backend anexa o Token ao cabeçalho da requisição HTTP em tempo real.',
    'auth.zero_exposure': 'Zero Exposição: as suas credenciais nunca passam pelo contexto da IA.',
    'auth.full_control': 'Controle Total: tem controlo visual do que está a enviar.',
    'auth.token_management': 'O resultado? Você obtém todo o poder de automação da IA, com a garantia de que suas chaves de acesso e senhas estão isoladas e protegidas contra alucinações do modelo.',
    'auth.security_full_title': '🔒 Autenticação Segura e Direta',
    'auth.security_full_desc': 'Para garantir a máxima segurança, o login é realizado diretamente pela nossa interface web — e não delegado à Inteligência Artificial.',
    'auth.security_why_safer': 'Por que isso é mais seguro?',
    'auth.security_zero_exposure': 'Zero Exposição: Suas credenciais (senha ou telefone) nunca passam pelo contexto ou memória da IA, evitando qualquer risco de vazamento ou "prompt injection".',
    'auth.security_full_control': 'Controle Total: Você tem o controle visual exato do que está enviando para a API original.',
    'auth.security_token_title': 'Como gerimos o seu Token?',
    'auth.security_token_desc': 'Após o login bem-sucedido, a API retorna um Token de acesso. Nós capturamos esse Token e o injetamos automaticamente de forma criptografada nas chamadas subsequentes que a IA fizer. A IA apenas executa as ações, mas nunca "vê" ou armazena o seu token de sessão.',
    'auth.security_peace': 'Trabalhe com a IA com a tranquilidade de que as suas credenciais estão protegidas.',
  },
  en: {
    'nav.about': 'About',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.login': 'Sign in',
    'nav.enter': 'Sign In',
    'nav.go_to_dashboard': 'Go to Dashboard',
    'hero.tag': 'v1.0.0',
    'hero.title': 'Convert any REST API to MCP',
    'hero.sub': 'Connect your REST APIs to Claude, GPT or any MCP client in seconds. 100% cloud, no local server needed.',
    'hero.cta': 'Create Free Server',
    'hero.badge.seconds': 'Seconds to configure',
    'hero.badge.zero': 'Zero code required',
    'hero.badge.openapi': 'Supports OpenAPI 3.0 + Swagger 2.0',
    'hero.badge.auth': 'Secure Web Auth',
    'hero.cli.label': 'Official CLI',
    'hero.cli.desc': 'Manage your MCP servers straight from the terminal: create, link to your editor (VS Code, Claude, Cursor, OpenCode...) and check logs without leaving the command line.',
    'hero.cli.copy': 'Copy',
    'hero.cli.copied': 'Copied!',
    'about.label': '// 01 — About the project',
    'about.title': 'Why does this project exist?',
    'about.p1': 'Modern LLMs like Claude and GPT have incredible capabilities, but they cannot directly interact with REST APIs. The MCP (Model Context Protocol) solves this, but requires each API to have a dedicated MCP server.',
    'about.p2': 'rest2mcp removes this barrier: provide your OpenAPI/Swagger spec URL, and the server automatically generates MCP tools — without writing a single line of code.',
    'about.problem': 'Each REST API needs a dedicated MCP server. Creating one manually for each endpoint is impractical.',
    'about.solution': 'Automatic conversion of OpenAPI/Swagger specs to MCP tools — 100% cloud, no local installation.',
    'about.how': 'How it works?',
    'about.how_desc': 'rest2mcp runs on our cloud infrastructure. Provide your OpenAPI/Swagger spec URL and the server automatically generates the corresponding MCP tools — no local installation needed. The LLM can call endpoints, log in, and interact with the API as if it were a native extension.',
    'security.label': '// Security',
    'security.title': 'Your privacy is our priority.',
    'security.badge': 'Zero-Knowledge Architecture',
    'security.stateless': 'Stateless',
    'security.stateless_desc': 'We do not store credential databases. Tokens live only in ephemeral memory during the session.',
    'security.e2e': 'End-to-End',
    'security.e2e_desc': 'The connection is made directly between the LLM and your infrastructure through our bridge.',
    'security.audit': 'Auditable',
    'security.audit_desc': 'Transparent logs for you to monitor exactly what the AI is accessing.',
    'features.label': '// 03 — Features',
    'features.title': 'Everything you need, ready to use.',
    'features.desc': 'Eight features that make rest2mcp the fastest choice to connect LLMs to your APIs.',
    'feat.anyapi': 'Any API, Zero Code',
    'feat.anyapi_desc': 'Just configure the OpenAPI spec URL. The server automatically generates all MCP tools — no development needed.',
    'feat.auth': 'Secure Web Auth',
    'feat.auth_desc': 'Login happens directly on our portal — your credentials never pass through the AI context. The token is automatically injected in subsequent calls.',
    'feat.merge': 'Multiple APIs + Merge',
    'feat.merge_desc': 'Combine multiple APIs into a single MCP server with namespaces. Supports merging local and remote servers.',
    'feat.compat': 'Full Compatibility',
    'feat.compat_desc': 'Fully compatible with OpenAPI 3.0 and 3.1 specifications, as well as the classic Swagger 2.0 format.',
    'feat.logs': 'Real-time Logs',
    'feat.logs_desc': 'Monitor all AI calls to your tools: method, status, duration, full request and response.',
    'feat.proxy': 'SSE + HTTP Proxy',
    'feat.proxy_desc': 'Supports Server-Sent Events (SSE) and Streamable HTTP. Persistent and continuous connections to your API.',
    'feat.secure': 'Secure Authentication',
    'feat.secure_desc': 'Secure login with Google, GitHub or email/password. Session management, password recovery and protected user profiles.',
    'feat.stripe': 'Stripe Payments',
    'feat.stripe_desc': 'Pro plan with secure payments via Stripe. Integrated checkout, automatic subscription management and webhook notifications.',
    'pricing.label': '// Plans',
    'pricing.title': 'Choose the best plan.',
    'pricing.desc': 'From hobby to enterprise — rest2mcp adapts to your needs.',
    'pricing.hobby': 'Hobby',
    'pricing.hobby_price': 'Free',
    'pricing.hobby_desc': 'For testing and experimentation',
    'pricing.hobby.feat1': '1 Active Server',
    'pricing.hobby.feat2': '1 Merge Server',
    'pricing.hobby.feat3': 'Last 24h logs',
    'pricing.hobby.feat4': '10 requests/minute',
    'pricing.hobby.feat5': 'SSE + HTTP Transport',
    'pricing.hobby.cta': 'Get Started Free',
    'pricing.pro': 'Pro',
    'pricing.pro_price': '$9.90',
    'pricing.pro_month': '/month',
    'pricing.pro_desc': 'For professional use',
    'pricing.pro.feat1': '10 Active Servers',
    'pricing.pro.feat2': '10 Merge Servers',
    'pricing.pro.feat3': 'Full logs (no expiration)',
    'pricing.pro.feat4': '100 requests/minute',
    'pricing.pro.feat5': 'High priority (no cold-start)',
    'pricing.pro.feat6': 'Private API support via Tunnel',
    'pricing.pro.cta': 'Subscribe Pro',
    'pricing.enterprise': 'Enterprise',
    'pricing.enterprise_price': 'Contact Us',
    'pricing.enterprise_desc': 'For organizations',
    'pricing.enterprise.feat1': 'Unlimited Servers',
    'pricing.enterprise.feat2': 'Unlimited Merge',
    'pricing.enterprise.feat3': 'Full logs + export',
    'pricing.enterprise.feat4': 'Custom rate limits',
    'pricing.enterprise.feat5': 'Dedicated support + SLA',
    'pricing.enterprise.cta': 'Contact Sales',
    'pricing.popular': 'POPULAR',
    'dashboard.label': '// Dashboard',
    'dashboard.title': 'Manage your servers in real time.',
    'dashboard.desc': 'Simple and straightforward interface to create, monitor and manage your MCP bridges.',
    'dashboard.my_servers': 'My Servers',
    'faq.label': '// FAQ',
    'faq.title': 'Frequently asked questions.',
    'faq.desc': 'Common developer questions about rest2mcp.',
    'faq.q1': 'Which specifications are supported?',
    'faq.a1': 'We support OpenAPI 3.0 and 3.1 natively, and also offer full compatibility with Swagger 2.0.',
    'faq.q2': 'Do I need to install anything?',
    'faq.a2': 'No. rest2mcp runs 100% in the cloud. You only need an MCP client (VS Code, Claude Desktop, Cursor, etc.).',
    'faq.q3': 'How does authentication work?',
    'faq.a3': 'The server automatically detects login endpoints in the spec. The LLM can log in via MCP tool and the token is managed automatically. We also support OAuth (Google, GitHub).',
    'faq.q4': 'Can I combine multiple APIs?',
    'faq.a4': 'Yes. You can combine multiple APIs into a single MCP server. Each API maintains its separate context.',
    'faq.q5': 'What is the Merge Server feature?',
    'faq.a5': 'The Merge Server lets you unify multiple MCP servers (local or remote) under a single access point. The AI interacts with all tools in an integrated way.',
    'faq.q6': 'What are real-time logs?',
    'faq.a6': 'Every AI tool call is recorded: method, status, duration, request and response. You can filter, export (JSON/CSV) and inspect details.',
    'faq.q7': 'How does the Pro plan work?',
    'faq.a7': 'The Pro plan costs $9.90/month and gives you 10 servers, full logs, 100 req/min, high priority and private API support via tunnel. PayPal monthly subscription.',
    'contact.label': '// 04 — Contact & Support',
    'contact.title': 'Get in touch with us.',
    'contact.desc': 'Any questions, feedback or need personalized support? Send us a message directly.',
    'contact.name': 'Your name',
    'contact.email': 'Your email',
    'contact.subject': 'Message subject',
    'contact.message': 'Write your message here...',
    'contact.send': 'Send Message',
    'contact.or': 'Alternatively, you can email us directly at:',
    'config.label': '// 07 — Configuration',
    'config.title': 'Supported MCP Clients.',
    'config.desc': 'rest2mcp works with any MCP client. Just point to our cloud bridge.',
    'config.more': 'And more...',
    'footer.desc': 'Version 1.0.0 · Author: Matias Fernando',
    'footer.about': 'About the Project',
    'footer.support': 'Support',
    'footer.rights': '© 2026 rest2mcp. All rights reserved. No data is retained on our servers.',
    'login.title': 'Sign in to your Account',
    'login.sub': 'Select your preferred provider to continue',
    'login.google': 'Sign in with Google',
    'login.github': 'Sign in with GitHub',
    'login.email_divider': 'or use your email',
    'login.email_placeholder': 'Your email',
    'login.password_placeholder': 'Password',
    'login.confirm_placeholder': 'Confirm password',
    'login.forgot': 'Forgot my password',
    'login.submit': 'Sign In',
    'login.cancel': 'Cancel',
    'login.register_title': 'Create Account',
    'login.register_sub': 'Sign up to get started',
    'login.register_btn': 'Sign Up',
    'login.toggle_register': 'Don\'t have an account? Sign Up',
    'login.toggle_login': 'Already have an account? Sign In',
    'login.registered': 'Registration successful!',
    'login.check_email': 'Check your email. Verify your inbox (and spam).',
    'forgot.title': 'Reset Password',
    'forgot.sub': 'You will receive an email with instructions to reset your password',
    'forgot.email_placeholder': 'Your email',
    'forgot.send': 'Send Email',
    'forgot.cancel': 'Cancel',
    'forgot.sending': 'Sending...',
    'forgot.sent': 'Email sent! Check your inbox (and spam).',
    'paypal.title': 'Subscribe Pro',
    'paypal.sub': 'Complete your monthly subscription',
    'paypal.cancel': 'Cancel',
    'paypal.activated': 'Subscription activated!',
    'dashboard.nav.title': 'My Servers',
    'dashboard.online': 'online',
    'dashboard.offline': 'offline',
    'dashboard.copy_url': 'Copy Connection URL',
    'dashboard.live_logs': 'Live Logs',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.create': 'Create',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'tool.params': 'Parameters:',
    'tool.none': 'none',
    'tool.no_args': 'This tool requires no arguments.',
    'tool.run': 'Run',
    'tool.running': 'Running...',
    'tool.result': 'Result',
    'tool.raw': 'Raw JSON',
    'tool.formatted': 'Formatted',
    'tool.error': 'Tool returned error',
    'tool.run_error': 'Error running tool',
    'tool.array_hint': 'JSON array or comma-separated',
    'store.loading': 'Loading store...',
    'store.error': 'Failed to load servers. Try again.',
    'store.empty': 'No servers found.',
    'store.load_more': 'Load more servers',
    'pagination.prev': 'Previous',
    'pagination.next': 'Next',
    'store.remote': 'Remote',
    'store.hybrid': 'Hybrid',
    'store.local': 'Local',
    'store.tools': 'tools',
    'store.modal.title': 'MCP Store',
    'server.edit': 'Edit',
    'server.inspect': 'Inspect',
    'server.tools': 'View Tools',
    'server.merge': 'Merge',
    'server.deactivate': 'Deactivate',
    'server.activate': 'Activate',
    'server.delete': 'Delete',
    'server.unmerge': 'Unmerge',
    'server.created': 'Server created successfully.',
    'server.deleted': 'Server removed successfully.',
    'server.activated': 'Server activated successfully.',
    'server.deactivated': 'Server deactivated successfully.',
    'server.merged': 'Merged server created successfully.',
    'server.unmerged': 'Merge undone successfully.',
    'modal.create.title': 'Create Server',
    'modal.create.name': 'Server Name',
    'modal.create.spec_url': 'OpenAPI Spec URL',
    'modal.create.transport': 'Transport',
    'modal.create.btn': 'Create Server',
    'modal.create.creating': 'Creating...',
    'modal.edit.title': 'Edit Server',
    'modal.merge.title': 'Merge Servers',
    'modal.merge.target': 'Select a server...',
    'modal.merge.btn': 'Create Merged Server',
    'modal.merge.creating': 'Creating...',
    'modal.merge.local': 'Merge servers in rest2mcp with automatic namespace',
    'modal.merge.sandbox': 'Temporary installation of an MCP server via npx, pipx or uv (or custom JSON)',
    'menu.inspect': 'Inspect',
    'menu.edit': 'Edit',
    'menu.tools': 'View Tools',
    'menu.merge': 'Merge',
    'menu.deactivate': 'Deactivate',
    'menu.activate': 'Activate',
    'menu.delete': 'Delete',
    'menu.unmerge': 'Unmerge',
    'confirm.delete': 'Remove this server permanently?',
    'confirm.unmerge': 'Undo merge of this server?',
    'tools.modal.title': 'Tools:',
    'tools.modal.loading': 'Loading tools...',
    'tools.modal.empty': 'No tools available.',
    'tools.modal.close': 'Close',
    'auth.login_error': 'Invalid or expired token',
    'auth.session_ended': 'Session ended.',
    'auth.login_redirect': 'Redirecting to',
    'env.title': 'Environment Variables / Headers',
    'env.auth_placeholder': 'Bearer your-token-here',
    'env.auth_desc': 'Authentication token for remote servers',
    'merge.local_tab': 'Local',
    'merge.sandbox_tab': 'Sandbox',
    'merge.name_placeholder': 'Ex: My API (Merged)',
    'merge.error_required': 'Enter the merged server name.',
    'merge.error_json': 'Invalid JSON. Check syntax.',
    'merge.error_target': 'Select a target server.',
    'merge.error_env': 'Fill in all required environment fields.',
    'merge.search_label': 'Search servers...',
    'merge.sort_label': 'Sort',
    'not_found': 'Server not found',
    'server.not_found': 'Server ID not available',
    'profile.plan': 'plan',
    'profile.servers': 'servers',
    'profile.token_hint': 'Use this token in the Authorization: Bearer <token> header to authenticate API requests.',
    'login.error': 'Failed to load store servers',
    'toolcall.error': 'Error listing tools',
    'dashboard.new_server': 'New Server',
    'dashboard.loading_servers': 'Loading servers',
    'dashboard.load_error': 'Error loading servers:',
    'dashboard.retry': 'Try again',
    'dashboard.empty': 'No servers yet.',
    'dashboard.empty_hint': 'Click + New Server to get started.',
    'dashboard.page_sub': 'Manage your MCP bridges in the cloud',
    'dashboard.current_plan': 'Current Plan',
    'dashboard.hobby_badge': '✦ Hobby',
    'dashboard.active_servers': 'Active servers',
    'dashboard.log_retention': 'Log retention',
    'dashboard.gateway': 'Gateway',
    'dashboard.servers_label': 'Servers',
    'dashboard.plan_label': 'Plan',
    'dashboard.subscription': 'Subscription',
    'dashboard.subscribe': 'Subscribe Pro — $9.90/month',
    'dashboard.logs_title': 'Logs',
    'dashboard.filter_tool': 'Filter tool...',
    'dashboard.all': 'All',
    'dashboard.success_2xx': '2xx Success',
    'dashboard.error_4xx': '4xx Error',
    'dashboard.error_5xx': '5xx Error',
    'dashboard.waiting_logs': 'Waiting for activity...',
    'dashboard.no_calls': 'No calls yet...',
    'dashboard.clear_logs_confirm': 'Clear all logs for this server?',
    'dashboard.logs_cleared': 'Logs cleared successfully.',
    'dashboard.clear_logs_error': 'Error clearing logs:',
    'dashboard.gateway_ok': 'ok · {count} active',
    'dashboard.gateway_offline': 'offline',
    'dashboard.api_unavailable': 'API unavailable',
    'dashboard.merged_badge': 'Merged',
    'dashboard.log_detail_title': 'Log Detail',
    'dashboard.log_detail_sub': 'Full request and response',
    'dashboard.request_body_label': 'Request Body',
    'dashboard.response_body_label': 'Response Body',
    'dashboard.empty_body': '(empty)',
    'dashboard.export_json': 'Export JSON',
    'dashboard.export_csv': 'Export CSV',
    'dashboard.clear_logs_btn': 'Clear logs',
    'dashboard.refresh': 'Refresh',
    'dashboard.log_server_placeholder': 'Server...',
    'dashboard.now': 'now',
    'dashboard.options': 'More options',
    'profile.token': 'Access Token (Bearer)',
    'profile.copy': 'Copy',
    'profile.copied': 'Copied ✓',
    'profile.account_details': 'Account Details',
    'profile.user_id': 'User ID',
    'profile.email': 'Email',
    'profile.provider': 'Provider',
    'profile.password': 'Password',
    'profile.change_password': 'Change Password',
    'profile.new_password': 'New password (min. 6 characters)',
    'profile.password_min': 'New password must be at least 6 characters.',
    'profile.password_min_reset': 'Password must be at least 6 characters.',
    'profile.service_unavailable': 'Service unavailable. Try reloading the page.',
    'profile.saving': 'Saving...',
    'profile.password_changed': 'Password changed successfully!',
    'profile.resetting': 'Resetting...',
    'profile.password_reset_success': 'Password reset successfully!',
    'profile.logout': 'Sign Out',
    'profile.servers_label': 'Servers',
    'profile.rpm_label': 'RPM',
    'profile.member_since': 'Member since',
    'profile.not_authenticated': '(not authenticated)',
    'profile.user_default': 'User',
    'profile.close_btn': 'Close',
    'profile.view_profile': 'View profile',
    'profile.sign_out_title': 'Sign out',
    'profile.reset_password_title': 'Reset Password',
    'profile.reset_password_sub': 'Choose a new password for your account',
    'profile.new_password_field': 'New Password',
    'profile.password_min_chars': 'Min 6 characters',
    'profile.reset_password_btn': 'Reset Password',
    'auth.redirecting': 'Redirecting to',
    'auth.ending_session': 'Ending session...',
    'auth.popup_blocked': 'Popup blocker prevented opening MCP Inspector.\nOpen manually:',
    'server.toggle_on': 'activated',
    'server.toggle_off': 'deactivated',
    'server.toggle_error': 'Error changing status:',
    'server.delete_error': 'Error removing:',
    'server.unmerge_error': 'Error undoing merge:',
    'server.name_required': 'Enter server name.',
    'server.spec_required': 'Enter OpenAPI Spec URL.',
    'server.edit_name_required': 'Name cannot be empty.',
    'server.edit_spec_url_required': 'Enter OpenAPI Spec URL.',
    'server.create_error': 'Error creating server:',
    'server.update_ok': 'Server updated successfully.',
    'server.update_error': 'Error updating server:',
    'server.merge_name_required': 'Enter the merged server name.',
    'server.merge_config_required': 'Enter the server JSON configuration.',
    'server.merge_error_json': 'Invalid JSON. Check syntax.',
    'server.merge_error_env': 'Fill in all required environment fields.',
    'server.merge_command_required': 'JSON needs command or mcpServers field.',
    'server.merge_target_required': 'Select a target server.',
    'server.merge_error_local': 'Error in local merge:',
    'server.merge_error_remote': 'Error in remote merge:',
    'server.merge_error_sandbox': 'Error in sandbox merge:',
    'server.inspector_starting': 'Starting MCP Inspector...',
    'server.inspector_no_url': 'Backend did not return an inspector URL.',
    'server.inspector_error': 'Error starting inspector:',
    'store.hosting': 'Hosting',
    'store.categories': 'Categories',
    'store.search_placeholder': 'Search MCP servers...',
    'store.sort_relevance': 'Relevance',
    'store.sort_stars': '★ GitHub Stars',
    'store.sort_tools': '🛠 Most tools',
    'store.sort_name_asc': 'Name A-Z',
    'store.sort_name_desc': 'Name Z-A',
    'store.modal_sub': 'Find and install public MCP servers',
    'store.package_not_found': "Package '{pkg}' not found on npm. Fallback activated.",
    'store.fallback_activated': 'Fallback activated.',
    'store.using_alternative': 'Using:',
    'store.install_btn': 'Install from store',
    'merge.local_title': 'Servers in rest2mcp',
    'merge.local_desc': 'Merge servers in rest2mcp with automatic namespace',
    'merge.sandbox_desc': 'Temporary installation of an MCP server via npx, pipx or uv (or custom JSON)',
    'merge.sandbox_title': 'Sandbox / JSON',
    'merge.merge_label': 'Merged Server Name',
    'merge.merge_placeholder': 'E.g.: Unified API',
    'merge.target_label': 'Target server',
    'merge.target_hint': 'rest2mcp server to merge with the source server',
    'merge.config_label': 'Config JSON',
    'merge.config_hint': 'MCP server command/args. Supports mcpServers, url (remote), command (stdio), tools (transformations) and env.',
    'modal.create.sub': 'Register a new API to be converted to MCP',
    'modal.create.name_placeholder': 'E.g.: My Main API',
    'modal.create.url_placeholder': 'https://api.example.com/openapi.json',
    'modal.create.transport_http': 'Streamable HTTP (recommended)',
    'modal.create.transport_sse': 'SSE (legacy)',
    'modal.edit.sub': 'Change MCP server settings',
    'modal.edit.name_label': 'Server Name',
    'modal.edit.name_placeholder': 'E.g.: My API',
    'modal.edit.transport_label': 'Transport',
    'modal.edit.status_label': 'Status',
    'modal.edit.status_online': 'Online',
    'modal.edit.status_offline': 'Offline',
    'modal.edit.saving': 'Saving...',
    'notifications.supabase_error': 'Failed to initialize Supabase:',
    'notifications.supabase_not_configured': 'Supabase not configured.',
    'notifications.paypal_error': 'Error processing payment.',
    'notifications.paypal_activated': 'Subscription activated!',
    'notifications.log_detail_error': 'Error loading log detail:',
    'dashboard.log_meta_tool': 'Tool',
    'dashboard.log_meta_method': 'Method',
    'dashboard.log_meta_status': 'Status',
    'dashboard.log_meta_duration': 'Duration',
    'dashboard.log_meta_date': 'Date',
    'auth.login_title': 'API Login',
    'auth.needs_login': 'Needs Login',
    'auth.authenticating': 'Authenticating…',
    'auth.authenticate': 'Authenticate',
    'auth.login_desc': 'Login happens directly in your browser — your credentials never pass through the AI context.',
    'auth.why_title': 'Why we prefer Web authentication over LLM?',
    'auth.why_desc': 'In modern AI integration architecture, your data security is the top priority. Allowing a Large Language Model (LLM) to handle passwords or log in on your behalf introduces unnecessary risks.',
    'auth.step1_title': '1. Direct Login (Human-in-the-loop)',
    'auth.step1_desc': 'When you enter your credentials on this portal, they travel directly from your browser to the target API. The AI agent is "blind" to this transaction.',
    'auth.step2_title': '2. Ephemeral Session Management',
    'auth.step2_desc': 'We receive the Token (JWT or similar) back from the API and store it securely in your MCP server\'s active session.',
    'auth.step3_title': '3. Transparent Injection',
    'auth.step3_desc': 'Whenever the AI needs to use a permission-requiring tool (like "create task" or "view profile"), our backend attaches the Token to the HTTP request header in real time.',
    'auth.zero_exposure': 'Zero Exposure: your credentials never pass through the AI context.',
    'auth.full_control': 'Full Control: you have visual control of what you are sending.',
    'auth.token_management': 'The result? You get all the automation power of AI, with the guarantee that your access keys and passwords are isolated and protected against model hallucinations.',
    'auth.security_full_title': '🔒 Secure & Direct Authentication',
    'auth.security_full_desc': 'To ensure maximum security, login happens directly through our web interface — not delegated to the Artificial Intelligence.',
    'auth.security_why_safer': 'Why is this safer?',
    'auth.security_zero_exposure': 'Zero Exposure: Your credentials (password or phone) never pass through the AI context or memory, avoiding any risk of leakage or prompt injection.',
    'auth.security_full_control': 'Full Control: You have exact visual control over what you are sending to the original API.',
    'auth.security_token_title': 'How do we manage your Token?',
    'auth.security_token_desc': 'After successful login, the API returns an access Token. We capture this Token and automatically inject it in encrypted form into subsequent calls made by the AI. The AI only executes actions, but never "sees" or stores your session token.',
    'auth.security_peace': 'Work with the AI with the peace of mind that your credentials are protected.',
  },
};

export const t = derived(lang, ($lang) => {
  const strings = dict[$lang] || dict.pt;
  return (key) => strings[key] || key;
});